project:
  type: book
  output-dir: docs

book:
  title: "Teoria Política I"
  author: Felipe Lamarca
  chapters:
    - index.qmd
    - part: Aulas
      chapters:
        - aulas/aula-1.qmd
        - aulas/aula-2.qmd
        - aulas/aula-3.qmd
        - aulas/aula-4.qmd
        
format:
  html:
    theme: 
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true



