# Aristóteles

## Anotações das leituras

### ARISTÓTELES. Política. Tradução de Mario da Gama Kury. São Paulo: Editora Madamu, 2021. Livros I, III, IV, V e VI.

#### **Livro I**

> Vemos que toda cidade é uma espécie de comunidade e toda comunidade se forma com vistas a algum bem, pois todas as ações de todos os homens são praticadas com vistas ao que lhes parece um bem; se todas as comunidades visam a algum bem, é evidente que a mais importante de todas elas e que inclui todas as outras tem mais que todas este objetivo e visa ao mais importante de todos os bens; ela se chama cidade e é a comunidade política. (1252a)

> Da mesma forma que em outras matérias é necessário decompor o conjunto até chegar a seus elementos mais simples (**estes são as menores partes de um todo**), com a cidade também, examinando os elementos dos quais ela se compõe discerniremos melhor, em relação a estas diferentes espécies de mando, qual é a distinção entre elas, e saberemos se é possível chegar a uma conclusão em bases científicas a propósito de cada afirmação feita pouco antes. **Se estudarmos as coisas em seu estágio inicial de desenvolvimento, quer se trate deste assunto ou de outros, teremos uma visão mais clara delas**. (1252a)

> Estas considerações deixam claro que a cidade é uma criação natural, e que o **homem é por natureza um animal social**, e um homem que por natureza, e não por mero acidente, não fizesse parte de cidade alguma, seria desprezível ou estaria acima da humanidade [...]. Agora é evidente que o homem, muito mais do que a abelha ou outro animal gregário, é um animal social. Como costumamos dizer,** a natureza nada faz sem um propósito, e o homem é o único entre os animais que tem o dom da fala**. (1253a)

> Na ordem natural a cidade tem precedência sobre a família e sobre cada um de nós individualmente, pois o todo deve necessariamente ter precedência sobre as partes; com efeito, quando todo o corpo é destruído pé e mão já não existem, a não ser de maneira equívoca, como quando se diz que a mão esculpida em pedra é mão, pois a mão nessas circunstâncias para nada servirá e **todas as coisas são definidas por sua função e atividade, de tal forma que quando elas já não forem capazes de perfazer sua função não se poderá dizer que são as mesmas coisas**; elas terão apenas o mesmo nome. (1253a)

> É claro, portanto, que cada cidade tem precedência por natureza sobre o indivíduo. De fato, se cada indivíduo isoladamente não é auto-suficiente, consequentemente em relação à cidade ele é como as outras partes em relação ao seu todo, e um homem incapaz de integrar-se na comunidade, o que seja auto-suficiente a ponto de não ter a necessidade de fazê-lo, não é parte de uma cidade, por ser um animal selvagem ou um deus. (1253a)

> Mandar e obedecer são condições não somente inevitáveis mas também convenientes. Alguns seres, com efeito, desde a hora de seu nascimento são marcados para ser mandados ou para mandar, e há muitas espécies de mandantes e mandados [...]. (p. 1254a)

> De conformidade com o que dizemos, é num ser vivo que se pode discernir a natureza do comando do senhor e do estadista: a alma domina o corpo com a prepotência de um senhor, e a inteligência domina os desejos com a autoridade de um estadista ou rei; estes exemplos evidenciam que para o corpo é natural e conveniente ser governado pela alma, e para a parte emocional ser governada pela inteligência -- a parte dotada de razão, enquanto para as duas partes estar em igualdade ou posições contrárias é nocivo em todos os casos. (1254b)

> A intenção da natureza é fazer também os corpos dos homens livres e dos escravos diferentes -- os últimos fortes para as atividades servis, os primeiros erectos, incapazes para tais trabalhos mas aptos para a vida de cidadãos. (1254b)

> Uma delas [artes] é natural e a outra não é, resultando de certa experiência e habilidade. Podemos iniciar o seu estudo com a seguinte observação: há duas maneiras de usar cada bem; ambos os usos se relacionam com o próprio bem, mas não se relacionam da mesma maneira -- uma é peculiar à coisa e a outra não lhe é peculiar. Tomemos como exemplo um sapato: ele pode ser calçado e pode ser permutado, e ambas as situações são maneiras de utilizar-se de um sapato; com efeito, mesmo quem permuta um sapato por dinheiro ou gêneros alimentícios, com quem o quer possuir, utiliza-o como sapato, embora não seja este o uso específico do sapato, que não foi criado com o propósito de ser permutado. (1257a)

> A causa deste estado de espírito ["todas as pessoas engajadas em enriquecer tentam aumentar o seu dinheiro ao infinito"] é o fato de a intenção destas pessoas ser apenas viver, e não viver bem; da mesma forma que o desejo de viver é ilimitado, elas querem que os meios de satisfazê-lo também sejam ilimitados. (1258a)

> Discutimos o ramo da arte de enriquecer que trata do supérfluo, definindo-o e explicando a razão de recorrermos a ele, e o ramo que trata do necessário, mostrando que este último, dedicado a assegurar a subsistência, é diferente do consagrado ao supérfluo e é por natureza parte da economia doméstica; ele não se assemelha ao ramo ilimitado, pois tem um limite. (p. 1258a)

> Como dissemos antes, esta arte se desdobra em duas, e um de seus ramos é de natureza comercial, enquanto o outro pertence à economia doméstica; este último ramo é necessário e louvável, enquanto o ramo ligado à permuta é justamente censurado (ele não é conforme à natureza, e nele alguns homens ganham à custa de outros). **Sendo assim, a usura é detestada com muita razão, pois seu ganho vem do próprio dinheiro, e não daquilo que levou à sua invenção**. (p. 1258b)

> Como dissemos antes, a ciência da economia doméstica tem três ramos -- um trata das relações entre senhor e escravo, outro das relações entre pai e filhos, e outro das relações entre marido e mulher, pois fazem parte da economia doméstica o comando da mulher e dos filhos pelo chefe da família (dela e deles como criaturas livres, embora não com a mesma forma de comando, mas o da mulher de maneira democrática e o dos filhos monarquicamente), com efeito, o macho é naturalmente mais apto para o comando do que a fêmea (exceto em alguns casos em que sua união se constitui contra a natureza) e o mais idoso e plenamente desenvolvido é amis apto que os mais jovens e imaturos.

> É evidente, portanto, que ambos devem possuir qualidades morais, mas que há diferenças entre suas qualidades, da mesma forma que há diferenças entre aqueles que são por natureza comandantes e comandados. Isto nos leva imediatamente de volta à natureza da alma: nesta, há por natureza uma parte que comanda e uma parte que é comandada, às quais atribuímos qualidades diferentes, ou seja, a qualidade do racional e a do irracional. É claro, então, que o mesmo princípio se aplica aos outros casos de comandante e comendado. Logo, há por natureza várias classes de comandantes e comandados, pois de maneiras diferentes o homem livre comanda o escravo, o macho comanda a fêmea e o homem comanda a criança. Todos possuem as várias partes da alma, mas possuem-nas diferentemente, pois o escravo não possui de forma alguma a faculdade de deliberar, enquanto a mulher a possui, mas sem autoridade plena, e a criança a te, posto que ainda em formação. [...]. Logo, o comandante deve possuir qualidades morais de forma perfeia, pois sua função, de maneira absoluta, é aquela de um organizador, e a razão é organizadora; os comandados, por outro lado, devem partilhar desta qualidade na medida em que lhes é conveniente (p. 1260a)

> Com efeito, uma vez que cada família é parte de uma cidade, e as pessoas a cujas relações nos referimos são partes de uma família, e que as qualidades das partes estão ligadas às do todo, impõe-se que a educação das crianças e das mulheres seja conduzida com vistas à forma de constituição adotada, se faz alguma diferença para a qualidade da cidade que as crianças tenham qualidades e que as mulheres tenham qualidades. (p. 1260b-1261a)

---

#### **Livro III**

> [...] é claro, portanto, que devemos primeiro investigar a natureza do cidadão, pois uma cidade é uma multidão de cidadãos, e qual é essencialmente a natureza do cidadão. (p. 1275a)

> Um cidadão integral pode ser definido por nada mais nem nada menos que pelo direito de administrar justiça e exercer funções públicas; algumas destas, todavia, são limitadas quanto ao tempo de exercício, de tal modo que não podem de forma alguma ser exercidas duas vezes pela mesma pessoa, ou somente podem sê-lo depois de certos intervalos de tempo pré-fixados; para outros encargos não há limitações de tempo no exercício de funções públicas. (1275b)

> Então, o que é um cidadão passa a ser claro depois destas considerações; afirmamos agora que aquele que tem direito de participar da função deliberativa ou da judicial é um cidadão da comunidade na qual ele tem este direito, e esta comunidade -- uma cidade -- é uma multidão de pessoas suficientemente numerosa para assegurar uma vida independente da outra. (1276a)

> Então, se for assim deveremos obviamente dizer que uma cidade é a mesma principalmente por causa de sua constituição, e ela pode ser designada, ou não, pelo mesmo nome, quer seus habitantes sejam os mesmos homens ou sejam inteiramente diferentes. Quanto a decidir se é justo que uma cidade deva ou não honrar seus compromissos depois de adotar outra constituição, isto é outra questão. (1276b)

> Depois do que acabamos de dizer, devemos perguntar se é possível afirmar que as qualidades de um homem bom são as mesmas de um bom cidadão, ou não são as mesmas. Se este ponto merece uma investigação, temos primeiro que determinar, pelo menos em linhas gerais, o que vem a ser a excelência de um cidadão. [...]. Da mesma forma [que marinheiros], um cidadão difere do outro, mas a preocupação de todos é a segurança de sua comunidade; esta comunidade é estabelecida graças à constituição, e consequentemente a bondade de um cidadão deve relacionar-se necessariamente com a constituição da cidade à qual ele pertence. [...] realmente, todos devem possuir a bondade do bom cidadão (esta é a condição indispensável para que uma cidade seja a melhor possível), mas é impossível que todos possuam a bondade de um homem bom, se não é necessário que todos os cidadãos sejam homens bons em uma cidade boa. (p. 1277a)

> Se as qualidades de um governante são as mesmas de um homem bom, e se o governado é também um cidadão, as qualidades do cidadão e as do homem não podem ser as mesmas de um modo geral, embora em algum caso particular possam sê-lo. (p. 1277b)

> [...] os cidadãos legítimos são os únicos que devem participar do governo, ou os artífices também devem ser considerados cidadãos para este fim?Se os homens que não ocupam funções de governo também deve ser considerados cidadãos, não é mais possível que a qualidade de todos os cidadãos sejam as mesmas, pois os artífices se tornam cidadãos. [...]. Com efeito, é verdade que nem todas as pessoas indispensáveis à existência de uma cidade devem ser contadas entre os cidadãos, porquanto os próprios filhos dos cidadãos não são cidadãos no mesmo sentido que os adultos: estes são cidadãos de maneira absoluta, enquanto aqueles são cidadãos presuntivos (são cidadãos, mas ainda incompletos). (p. 1278a)

> Tais fatos demonstram que há várias espécies de cidadãos, e que cidadão em sentido absoluto é o homem que partilha os privilégios da cidade, como está implícito em Homero. (1278b)

> Já dissemos em nossa primeira exposição, na qual estabelecemos os princípios relativos à economia doméstica e à posição do senhor em relação aos escravos, que o homem é por natureza um animal social; por isto mesmo, que os homens não necessitem de assistência mútua, ainda assim eles desejam viver juntos. Ao mesmo tempo eles são levados a reunir-se por terem interesses comuns, na medida em que cada um deles pode participar de uma vida melhor.

> Uma vez que constituição significa o mesmo que governo, e o governo é o poder supremo em uma cidade, e o mando pode estar nas mãos de uma única pessoa, ou de poucas pessoas, ou da maioria, nos casos em que esta única pessoa, ou as poucas pessoas, ou a maioria, governam tendo em vista o bem comum, estas constituições devem ser forçosamente as corretas; ao contrário, constituem desvios os casos em que o governo é exercido com vistas ao próprio interesse da única pessoa, ou das poucas pessoas, ou da maioria, pois ou se deve dizer que os cidadãos não participam do governo da cidade, ou é necessário que eles realmente participem. (p. 1279b)

> Os desvios das constituições mencionadas são a tirania, correspondendo à monarquia, a oligarquia à aristocracia, e a democracia ao governo constitucional; de fato, tirania é a monarquia governado no interesse do monarca, a oligarquia é o governo no interesse dos ricos, e a democracia é o governo no interesse dos pobres, e nenhuma destas formas governa para o bem de toda a comunidade. (p. 1279b)

> Surgem também dificuldades quando se quer saber quem deve deter o poder soberano da cidade, pois ele pode ser exercido pelas massas, pelos ricos, ou pelos homens bons, ou por um só homem melhor que todos os outros, ou por um tirano, mas todas estas alternativas parecem envolver consequências desagradáveis. (p. 1281a)

> A dificuldade levantada inicialmente, todavia, revela principalmente, e de maneira clara, que as leis verdadeiramente corretas devem ser soberanas, enquanto o alto funcionário, ou os altos funcionários, devem ter poderes para decidir somente os assuntos sobre os quais as leis não se mostram suficientemente precisas, por não ser fácil conseguir que um princípio geral abranja claramente todos os casos particulares. (p. 1282b)

> A pretensão ao exercício das altas funções deve fundar-se necessariamente em superioridade nas qualidades essenciais à existência da cidadania; logo, é razoável a pretensão dos homens bem nascidos, livres e ricos, a honrarias inerentes ao exercício de altas funções, pois deve haver homens livres e deve haver contribuintes para o tesouro público, já que não poderia existir uma cidade constituída inteiramente de homens pobres, nem de escravos. (p. 1283a)

> Todas estas considerações parecem provar, portanto, a inadequação de todos os princípios com base nos quais os homens têm a pretensão de governar e manter os demais sob o seu governo. Certamente mesmo contra os que reinvindicam a liderança do governo com fundamento em sua superioridade, e da mesma forma contra os que a reivindicam por causa de sua riqueza, a maioria pode apresentar uma reivindicação justa, pois nada impede que em certo momento a maioria possa ser coletivamente melhor e mais rica que a minoria, embora cada um de seus componentes de per si não o seja. (p. 1283b)

> É claro, então, que a legislação deve levar necessariamente em conta apenas as pessoas iguais em nascimento e capacidade, mas não pode haver lei alguma aplicável a homens como os descritos há pouco, porquanto eles mesmos são uma lei [...]. Foi por esta razão que as cidades governadas democraticamente insittuíram o ostracismo; estas cidades punham a igualdade acima de tudo, a ponto de condenar ao exílio homens tidos como excessivamente poderosos por sua riqueza, ou popularidade, ou alguma outra forma de força política, banindo-os da cidade por tempo determinado. (p. 1284a)

> Talvez seja conveniente, após a discussão dos assuntos anteriores, passar ao exame da monarquia, pois admitimos que ela é uma das formas corretas de governo. Vejamos, então, se é vantajoso para uma cidade ou uma nação que aspira a um bom governo ser dirigida por um rei, ou se alguma outra constituição é mais conveniente, ou se o governo monárquico é conveniente para algumas cidades, mas não para outras. É necessário, todavia, determinar primeiro se há uma única espécie de governo monárquico ou se há várias. (p. 1285a) 

> São estas as espécies de governo monárquico, em número de quatro: a primeira existia nos tempos heróicos e era exercida com o consentimento dos súditos, mas em esferas bem definidas, pois os reis eram comandantes militares, juízes e dirigentes das cerimônias religiosas; a segunda é o governo monárquico entre os povos bárbaros (um despotismo hereditário exercido de acordo com a lei); a terceira é o governo dos chamados _aisimnetas_ (trata-se de uma tirania eletiva); a quarta, finalmente, é o governo monárquico dos lacedemônios (ela pode ser definida simplesmente como um comando militar hereditário e vitalício). [...]. Existe, porém, uma quinta espécie de governo monárquico, quando um governante único exerce o poder soberano em todas as esferas, da mesma forma que cada povo e cidade é soberano sobre seus próprios assuntos; esta forma corresponde ao comando de um chefe de família sobre a casa [...]. (p. 1286a)

> O ponto de partida da nossa investigação [qual é melhor?] é perguntar se é mais conveniente ser governado pelos melhores homens ou pelas melhores leis. (p. 1287a)    

> Devemos definir primeiro, porém, qual é a natureza do governo monárquico, qual a do aristocrático e qual a do constitucional. Um povo capaz por natureza de produzir uma estirpe excelente nas qualidades necessárias ao comando político é um povo feito para a monarquia; um povo cujos componentes se sujeitam, como homens livres a serem governados por homens cujas qualidades os credenciam para o comando político é feito para a aristocracia, e o povo feito para o governo constitucional é aquele entre cujos componentes existe uma maioria combativa, constituída de homens capazes de mandar e obedecer alternadamente sob uma lei que distribui as funções de governo entre os homens de posses de acordo com seus méritos. (p. 1288a)

> Dissemos que as formas corretas de governo são três, e destas a exercida pelos melhores homens deve ser necessariamente a melhor, e esta é aquela em que em algum homem, ou uma família inteira, ou um grupo de homens, pode mostrar-se superior em qualidades a todos os demais cidadãos juntos, e na qual os cidadãos querem ser governados, e aquele homem, ou a família inteira, ou o grupo de homens, quer governar com o objetivo de dar a todos a vida mais desejável. Na primeira parte de nossa exposição demonstramos também que na melhor cidade as qualidades de um homem e de um cidadão devem ser necessariamente as mesmas; é evidente, então, que da mesma forma e pelos mesmos meios graças aos quais um homem se torna verdadeiramente bom, ele poderá constituir uma cidade a ser governada por uma aristocracia ou por uma monarquia, e se descobrirá que a mesma educação e os mesmos hábitos fazem um homem de bem e um homem apto a ser um estadista e um rei. (p. 1288b)

---

#### **Livro IV**

> Vemos que acontece o mesmo com a medicina, com a construção naval, com a confecção de roupas e todas as outras artes; é claro, então, que no caso das constituições cabe à mesma ciência averiguar qual a melhor entre elas, quais as características que uma delas deve ter para ser a melhor se não ocorrerem impedimentos externos a ela, e qual a constituição adequada de cada povo.

> Agora se pode ver com clareza qual destes dois desvios das respectivas formas corretas de constituição é o pior e qual deles ocupa o segundo lugar; com efeito, o desvio da primeira e mais divina forma é necessariamente o pior, da mesma forma que a monarquia, se não for apenas um novo, tem de existir fundamentada na extraordinária superioridade de quem é rei; então a tirania, sendo a prior forma, deve ser a mais afastada do governo constitucional, seguindo-se-lhe em segundo lugar a oligarquia (a aristocracia é amplamente separada daquela constituição), enquanto a democracia deve ser o desvio mais moderado. (p. 1289b)

> Melhor seria, por conseguinte, dizermos que há uma democracia quando os homens livres exercem o poder, e uma oligarquia quando os ricos o exercem, e que acidentalmente a classe soberana em uma democracia é numerosa, enquanto numa oligarquia é reduzida, porque há muitos homens nascidos livres e poucos ricos. Se as coisas não se passassem assim, supondo-se que as pessoas fossem escolhidas para as funções de governo pela estatura, como dizem que se faz na Etiópia, ou pela aparência, ter-se-ia uma oligarquia, pois tanto as pessoas de boa aparência quanto as de estatura elevada são pouco numerosas. (p. 1290b)

> Foi dito antes que há várias espécies de constituições e qual é a causa dessa variedade; mostraremos agora que há espécies diferentes tanto de democracia quanto de oligarquia. Essa afirmação se torna evidente diante do exposto, pois tanto o povo quanto os chamados notáveis se constituem de várias classes; uma das classes componentes do povo, por exemplo, é a de agricultores, outra é a que se dedica às artes e aos ofícios, outra é a classe comercial ocupada com os negócios de compra e venda, e outra se dedica às atividades ligadas ao mar [...]. (p. 1291b)

> A primeira espécie de democracia baseia-se principalmente na igualdade; nos termos da lei reguladora desta espécie de democracia, a igualdade significa que os pobres não têm mais direitos que os ricos, e nenhuma das duas classes é soberana de maneira exclusiva, mas ambas são iguais.

> Dá-se geralmente o nome de governos constitucionais somente àquelas formas baseadas na aludida mescla de constituições que se inclinam para a oligarquia, pois a educação e a nobreza se coadunam melhor com as classes mais ricas, e também se acredita que os ricos já possuem as coisas cuja conquista leva os malfeitores a fazer mal; por isto dá-se a denominação de "homens de bem" e "notáveis" aos ricos. (p. 1294a)

> As constituições chamadas aristocráticas, das quais falamos há pouco, ficam de certo modo fora do alcance da maior parte das cidades, e em outras se aproximam do chamado governo constitucional, sendo portanto adequado falar destas duas formas como se elas fossem uma só. Realmente, as conclusões a respeito de todas estas questões repousam nos mesmos fundamentos, pois se dissemos com razão na _Ética_ que a vida feliz é uma vida vivida de acordo com os ditames da moralidade e sem impedimentos e que a moralidade é um meio termo, segue-se necessariamente que a vida segundo este meio termo é a melhor -- um meio termo acessível a cada um dos homens. (p. 1295b)

> É igualmente claro que a comunidade política administrada pela classe média é a melhor, e que é possível governar bem as cidades nas quais a classe média é mais numerosa, e de preferência mais forte que as outras duas classes juntas, ou se assim não for, mais forte que qualquer delas isoladamente, pois ela pode fazer pender a balança a favor da classe à qual vier a juntar-se, impedindo, assim, a preponderância de um dos extremos contrários. (p. 1296a)

---

#### **Livro VI**

> Como existem várias espécies de democracia e igualmente de outras formas de governo, não será descabido examinar ao mesmo tempo quaisquer pontos restantes acerca destas espécies, e também determinar o tipo de organização apropriado e útil para cada uma delas. Deveremos investigar ainda as combinações de todos os sistemas de organização dos diversos poderes da cidade, já mencionados, pois estes sistemas, quando acoplados, provocam uma superposição de formas de governo, produzindo aristocracias oligárquicas e governos constitucionais tendendo para a democracia. (p. 1317a)

> Das quatro formas existentes de democracia, a melhor é a primeira em nossa enumeração, como dissemos nas dissertações anteriores a esta; ela é também a mais antiga de todas, mas quero dizer "primeira" como se se tratasse de uma classificação do povo que a constitui. O melhor povo é o constituído de agricultores, porquanto é possível implantar a democracia onde o povo em sua maioria vive da agricultura e da pecuária; pelo fato de não terem muitas posses, os agricultores estão sempre ocupados, e não podem por isto reunir-se frequentemente em assembleia, pois para satisfazerem suas necessidades básicas eles consomem todo o tempo no trabalho e não cobiçam os bens de seus vizinhos, e acham mais agradável trabalhar do que participar da política e ocupar funções públicas, já que o proveito decorrente do exercício das funções não é grande, e na realidade a maioria dos homens é mais ávida de ganhos que de honrarias. (p. 1318b)

> A última espécie de democracia -- aquela em que toda a população participa do governo -- não é suportável por todas as cidades, e não será fácil fazê-la durar muito tempo se ela não for bem constituída em suas leis e costumes. (p. 1319b)

## Anotações de aula

No texto do Aristóteles, vamos privilegiar a discussão sobre a teoria das formas de governo e o sentido mais geral do problema das formas de governo. Trata-se de uma tipologia baseada em quem detém o mando político e a finalidade (o exercício) desse poder político.

A ciência da política -- uma epísteme sobre o mundo da política depende de algumas coisas fundamentais: a reflexão sobre a política, para Aristóteles, parte de **dados empíricos**; parte da observação de como as cidades-estado funcionam, i.e., suas constituições. O primeiro passo do método aristotélico é a ideia de que a política é uma ciência prática sobre o mando político. O problema fundamental é olhar o funcionamento das cidades-estado gregas e ver como o mando político está distribuído.

O poder político está sempre divido entre um, por muitos ou por poucos. E o processo de mudança política que importa para Aristóteles é a mudança nas formas de governo. As formas políticas estão em constante tensão e, na prática, podem mudar. As formas de governo estão o tempo todo suscetíveis à instabilidade porque a dimensão da pólis é apenas uma dimensão da vida social -- o contra-conceito da pólis é o _oikos_, que é a vida doméstica, e o _polemos_, que é a guerra. Temos a vida da pólis (propriamente política, que estabelece quem manda e quem obedece), a vida doméstica e a guerra.

Se a política é o problema da ordem, essa ordem está o tempo todo suscetível à revolução (_stasis_, em grego). _Stasis_ é esse conflito que provoca mudanças nas formas de governo. A estabilização pode ser perturbada por conflitos externos e isso pode mudar a forma como o poder político está arranjado (do ponto de vista de quem manda e quem obedece).

Para Aristóteles, há mais ou menos uma expectativa de como a pólis se transforma do ponto de vista das formas de governo. Um exemplo clássico de Aristóteles: uma aristocracia tende a degenerar em oligarquia, porque os "melhores" começam a ter uma capacidade diferencial na ação coletiva e passam a acumular mais renda, o que, no fim das contas, pode fazer com que a aristocracia se degenere para se tornar o governo dos mais ricos, e não o governo dos melhores.

A própria descrição das formas de governo no Aristóteles pode mudar. Quando ele discute a diferença de aristocracia e oligarquia, isso parece muito distinto. O principal elemento de produção de conflito político é a insatisfação -- então, no fim das contas, as formas de governo são conceitos fluidos porque dependem de uma relação entre as formas em si e a crença das pessoas naqueles arranjos.

O governo constitucional é a melhor forma de governo, porque ele é o balanceamento entre oligarquia e democracia. Os indivíduos se organizam em comunidades políticas e, quanto menos existe uma diferença brutal de riqueza, menos conflito existe. Mas, é claro, como o mundo social é um mundo em mudança, essa não é a única origem do conflito. 

A origem do conflito político é, num certo sentido para Aristóteles, anterior à política. A política é uma solução, porque ela estabiliza quem manda e quem obedece. A ideia de que você pode saltar de uma situação de conflito para uma situação de ordem não faz qualquer sentido para o pensamento aristotélico, a despeito do fato de que os homens podem sair de uma situação de conflito porque os homens são naturalmente sociáveis.

A discussão sobre o que é um bom governo é normativa. Uma das finalidades que a natureza humana impõe ao homem é a sociabilidade e a vivência em sociedade, mas o conflito também é uma constante que pode levar o homem ao conflito. Portanto, o problema do bom governo é a estabilização do conflito de maneira mais eficaz -- para Aristóteles, a _politeia_ (i.e., o governo constitucional). **As melhores formas de governo são mistas, porque os conceitos políticos são abstrações de relações reais de conflito**, que são fundamentalmente relações de natureza material.

Diferença entre _demos_ (povo) e _pletos_ (multidão): a democracia é ruim quando é tomada pela multidão, e não pelo povo. A multidão é o conjunto de indivíduos agindo por meio da violência. Demos é o conjunto de indivíduos que fazem parte de uma comunidade política reunidos em assembleia. O problema não é o demos, mas quando esse conjunto de indivíduos age como multidão (massa, como modernamente chamamos). A relação entre massa e tirania é a relação entre carisma e os seguidores do líder carismático, pensando numa abordagem Weberiana. A relação entre massa e líder é um problema clássico da teoria política e está presente também em Aristóteles. Povo é como se fosse a forma institucionalizada dessa massa -- esse é o problema da democracia. O governo constitucional é uma democracia com um certo componente aristocrático, que é a ideia de que o governo é exercido por aqueles escolhidos com base nos seus méritos.

O homem (sexo masculino) é naturalmente sociável e naturalmente igual aos seus semelhantes. A forma ideal de governo é a aristocracia porque a distinção entre iguais é reconhecida por reconhecimento mútuo; e a oligarquia é a pior forma de governo porque a distinção é reconhecida compulsoriamente pela riqueza. Então existem essas camadas de igualdade e desigualdade. O indivíduo tem finalidades naturais -- em comunidade, a finalidade é uma boa ordem (que não seja mediada pelos interesses particulares), mas o indivíduo também tem como finalidade a perfeição das suas virtudes particulares. Quando as virtudes são reconhecidas pelos indivíduos livres e iguais, essa é a melhor comunidade política possível. É óbvio que se a gente consegue identificar em unanimidade que algum(ns) indivíduo(s) é(são) melhor(es) que os outros, nós vamos querer que ele(s) governe(m).

Se numa democracia os indivíduos são todos iguais e não existem distinções de capacidades naturais dos indivíduos, como as funções da pólis são definidas? Quem vai exercer cada poder? Sorteio! A forma de escolha fundamental numa democracia é não representativa. **A representação política é fundamentalmente aristocrática:** você precisa qualificar o exercício do poder político e eleger os melhores. A representação é a produção de uma distinção, até hoje. A escolha democrática é o sorteio, e a escolha aristocrática é a representação, movida pela ideia de capacidade.

Há uma dimensão da vida social em que nós não estamos dispostos a reconhecer a aleatoridade de quem vai exercer aquela função: **a guerra**. A guerra expõe a materialidade da necessidade da diferença. Ela traz a dimensão inevitavelmente aristocrática da vida social: a capacidade física ordena as pessoas entre mais capazes e menos capazes. **Então como na política a gente pode supor que essa distinção seja dispensável?** É por isso que a democracia é problemática para o Aristóteles.

A tirania não é uma condição exclusiva, mas ela é possível em todas as formas de governo. À medida em que as decisões vão sendo tomadas de forma cada vez mais discricionária (i.e., sem mediação de regras coletivas de tomada de decisão, e sim baseadas no interesse pessoal daquele que decide), acompanhada do acúmulo de riqueza, isso vai tornando o poder político cada vez mais tirânico. E aí, com isso, os oligarcas dão força às massas, que se rebelam contra eles e estabelecem a democracia.

Segundo Aristóteles, a melhor constituição não é só a melhor, mas a mais exequível. As instituições precisam ser capazes de canalizar o conflito, então a constituição precisa ser capaz de lidar com ele. Não tem como você tem uma oligarquia ou uma democracia, porque o risco de transbordar para o conflito é constante. Uma constituição não é apenas uma ordem normativa ideal, mas aquilo que é possível dentro de uma característica social e material de uma comunidade política.

O centro da argumentação do Aristóteles gira em torno da democracia e da oligarquia, porque elas figuram um conflito político fundamental, que é entre ricos e pobres. A democracia é o governo dos pobres, e a oligarquia é o governo dos ricos. Dentre as condições de existência da democracia há a isonomia: as diferenças existem, mas elas não produzem institucionalmente regras que diferenciem os cidadãos. A democracia pode, por exemplo, ser desvirtuada pelos demagogos, que motivam o uso privatista das maiorias -- o povo se transforma numa espécie de monarca múltiplo, numa unidade composta de muitos, já que muitos são coletivamente soberanos. Para Aristóteles, isso é bastante semelhante à tirania, porque o espírito é o mesmo.

O que, então, qualifica a democracia? O fato de que o povo reunido em assembleia constitui uma forma de governo estável por meio de regras, e que o exercício desse poder político vai ser exercido por indivíduos escolhidos pelo seu mérito -- **a _politeia_, ou governo constitucional** na tradução. Quando você limita mais os critérios de participação, essa forma se inclina para a o oligarquia; e quando você abre demais, se inclina à democracia. 

O **governo constitucional, por excelência, é uma mescla da democracia em da oligarquia**: existe isonomia, mas também existe distinção entre os cidadãos -- figurada pela representação política -- com base no mérito pessoal.

Revolução, para Aristóteles, é mudar a forma de governo. Em toda parte, elas são causadas pela desigualdade, mas especificamente nas situações em que as classes desiguais não participam proporcionalmente da mesma maneira do poder. Para Aristóteles, o que produz estabilidade institucional é o equilíbrio entre ricos e pobres. O mundo é caracterizado por essa desigualdade, mas é geralmente o desejo de igualdade (material) que leva a revoluções. O fato de que as pessoas se identificam como materialmente "piores" gera revoluções porque eles podem tentar se apossar das riquezas da minoria. 

No governo em que os cidadãos não têm nenhum mecanismo de ação política, identifica-se uma tirania. Só quem age -- de modo arbitrário, violento e não-político (porque não há construção de bem comum) -- é o tirano. 

Em resumo: a ideia de regras institucionais e de formas de governo são formas de estabilizar o mando político em uma sociedade permanentemente em conflito. A forma que essas instituições tomam depende fundamentalmente do conflito. A forma de governo que produz leis que permitem uma maior estabilidade é o governo constitucional, sobretudo se o diagnóstico for de que a pólis em questão é dividida pelo conflito entre ricos e pobres.

Para os pensadores de soberania moderna (Hobbes, por exemplo), existe uma forma legítima de constituição do poder político. A soberania é um modo de constituir a fonte da decisão política de modo incontornável, inquestionável.