---
title: "Maquiavel I"
author:
  - name: Felipe Lamarca
    email: felipelamarca@iesp.uerj.br
fontsize: 12pt
---

## Anotações das leituras

### MAQUIAVEL, Nicolau. Discursos sobre a primeira década de Tito Lívio -- Livro Primeiro. São Paulo: Martins Fontes, 2007.

> Muitos autores insistiram em atribuir a Maquiavel a paternidade da moderna ciência política. Vendo em suas obras uma ruptura radical com as antigas filosofias e o estabelecimento de parâmetros objetivos para a análise da vida política, acreditaram poder retirar de seus escritos os conceitos necessários para a construção de um discurso científico sobre a vida em comum dos homens. (p. XXXIX)

> Desejando, pois, afastar os homens deste erro, julguei necessário escrever, acerca de todos os livros de Tito Lívio que não nos foram tolhidos pelos malefícios dos tempos, aquilo que, do que sei das coisas antigas e modernas, julgar necessário ao maior entendimento deles, para que aqueles que lerem estes meus comentários possam retirar deles mais facilmente a utilidade pela qual se deve procurar o conhecimento das histórias. E, ainda que essa empresa seja difícil, ajudado por aqueles que me animaram a incumbir-me desse fardo, creio carregá-lo de tal modo que a algum outro será breve o caminho que restar para levá-lo até o destino. (p. 7)

> Quem ler a história do princípio da cidade de Roma da forma como tudo foi ordenado e por quais legisladores, não se admirará de que tanta _virtú_ se tenha mantido por vários séculos naquela cidade; e de que depois tenha surgido o império que aquela república atingiu. E, para discorrer antes sobre o seu nascimento, direi que todas as cidades são edificadas, ou pelos homens nascidos no lugar onde são edificadas, ou por forasteiros.

> Portanto, como só o poder dá segurança aos homens, é necessário fugir a essa esterilidade da terra e pôr-se em lugares fertilíssimos, onde, podendo a população ampliar-se graças à uberdade do solo, os homens consigam defender-se de quem os ataque e oprimir quem quer se oponha à sua grandeza.

> Assim, pode considerar-se feliz a república à qual caiba por sorte um homem tão prudente que lhe dê leis de tal modo ordenadas que seja possível viver com segurança sob tais leis, sem precisar corrigi-las. E vê-se que Esparta as observou por mais de oitocentos anos sem as corromper ou sem nenhum tumulto perigoso: e, pelo contrário, é em certo grau infeliz a cidade que, não tendo encontrado um ordenador prudente, precisou reordenar-se por si mesma. (p. 13)

> Portanto, para discorrer sobre as ordenações da cidade de Roma e os acontecimentos que a levaram à perfeição, direi o que dizem alguns que escreveram sobre as repúblicas, ou seja, que há nelas um dos três estados, chamados principado, optimates e popular; e que aqueles que ordenam uma cidade devem voltar-se para um deles, segundo o que lhes pareça mais apropriado. Outros -- mais sábios, segundo a opinião de muitos -- são de opinião que existem seis formas [_ragioni_] de governo, das quais três são péssimas e três são boas em si mesmas, mas tão fáceis de corromper-se que também elas vêm a ser perniciosas. Os bons são os três acima citados; os ruins são outros três que desses três decorrem; e cada um destes se assemelha àquele que lhe está próximo, e facilmente passam de um a outro: porque o principado facilmente se torna tirânico; os optimates com facilidade se tornam governo de poucos; o popular sem dificuldades se torna licencioso. De tal modo que, se um ordenador de república ordena um desses três estados numa cidade, o ordena por pouco tempo, pois nada poderá impedir que resvale para o seu contrário, pela semelhança que têm neste caso a virtude [_virtute_] e o vício. (p. 14)

> Nascem tais variações de governo ao acaso entre os homens: porque no princípio do mundo os habitantes, que eram escassos, viveram durante algum tempo dispersos como animais; depois, multiplicando-se, reuniram-se em grupos, e, para poderem melhor defender-se, começaram a respeitar aquele que, dentre eles, fosse mais forte e corajoso, e, fazendo dele seu dirigente, obedeciam-no. (p. 14)

> Mas, como depois se começou a ser príncipe por sucessão, e não por escolha, logo os herdeiros começaram a degenerar e, deixando as obras virtuosas, acreditavam que os príncipes nada mais precisassem fazer senão sobrepujar os outros em suntuosidade, lascívia e em todos os outros tipos de licença: de modo que, começando a ser odiado, o príncipe, temendo por tal ódio, logo passou do temor ao ataque, e rapidamente nasceu a tirania. (p. 15)

> Digo, portanto, que todos esses modos são nocivos, tanto pela brevidade da vida que há nos três bons quanto pela malignidade que há nos três ruins. Assim, sempre que tiveram conhecimento desse defeito, aqueles que prudentemente ordenam leis evitaram cada um desses modos por si mesmos e escolheram algum que tivesse um pouco de todos, por o julgarem mais firme e mais estável; **porque, quando numa mesma cidade há principado, optimates e governo popular, um toma conta do outros.** (p. 17, grifo meu)

> Como demonstram todos aqueles que discorrem sobre a vida civil e todos os exemplos de que estão cheias todas as histórias, quem estabelece uma república e ordena suas leis precisa pressupor que todos os homens são maus [_rei_] e que usarão a malignidade de seu ânimo sempre que para tanto tiverem ocasião; e quando alguma maldade se oculta por algum tempo, assim procede por alguma razão oculta que não se conhece porque não se teve experiência do contrário; mas essa razão um dia é posta a descoberto pelo tempo, que, segundo dizem, é o pai da verdade. (p. 20)

> Direi que quem condena os tumultos entre os nobres e a plebe parece censurar as coisas que foram a causa primeira da liberdade de Roma e considerar mais as assuadas e a grita que de tais tumultos nasciam do que os bons efeitos que eles geravam; **e não consideram que em toda república há dois humores diferentes, o do povo, e o dos grandes, e que todas as leis que se fazem em favor da liberdade nascem da desunião deles, como facilmente se pode ver que ocorreu em Roma**; porque dos Tarquínios aos Gracos, durante mais de trezentos anos, os tumultos de Roma raras vezes redundaram em exílio e raríssimas vezes em sangue. Portanto, não se pode dizer que tais tumultos sejam nocivos, nem que tal república fosse dividida, se em tanto tempo, em razão de suas diferenças, não mandou para o exílio mais de oito ou dez cidadãos, matou pouquíssimos e não condenou muitos ao pagamento de multas. (p. 21-22)

> Portanto, é necessário examinar qual dessas repúblicas fez melhor escolha. E, se remontássemos às razões, haveria argumentos de ambas as partes; mas, se examinássemos os resultados ficaríamos do lado dos nobres, visto que a liberdade de Esparta e de Veneza teve vida mais longa que a de Roma. E, indo às razões, direi, vendo primeiro o lado dos romanos, que se deve dar guarda de uma coisa àqueles que têm menos desejo de usurpá-la. **E sem dúvida, se considerarmos os objetivos dos nobres e o dos plebeus [_ignobili_], veremos naqueles grande desejo de dominar e nestes somente o desejo de não ser dominados e, por conseguinte, maior vontade de viver livres, visto que podem ter menos esperança de usurpar a liberdade do que os grandes**; de tal modo que, sendo os populares encarregados da guarda de uma liberdade, é razoável que tenham mais zelo e que, não podendo eles mesmos apoderar-se dela, não permitirão que outros se apoderem. Por outro lado, quem defende a ordenação espartana e veneziana diz que quem põe a guarda nas mãos de poderosos realiza duas boas ações: uma é satisfazer mais à ambição deles, que, tendo mais participação na república com tal bastão em mãos, têm mais motivo para contentamento; outra é que negam certo tipo de autoridade aos ânimos inquietos da plebe, razão de infinitas dissensções e tumultos numa república, capazes de causar alguma reação desesperada à nobreza, o que, com o tempo, produzirá maus efeitos. (p. 24-25)

> No entanto, no mais das vezes estes [enormes tumultos] são causados por aqueles que mais possuem, porque o medo de perder gera neles as mesmas vontades que há nos que desejam conquistar; pois os homens são acham que possuem com segurança o que têm quando acabam de conquistá-lo do outro. E há muitos que, possuindo muito, podem com mais poder e maior efeito [_moto_] provocar mudanças. E também há muitos cujo comportamento incorreto e ambicioso acende no peito de quem nada possui o desejo de possuir, seja para vingar-se dos que possuem, espoliando-os, seja para poderem entrar na posse das riquezadas e das honrarias que percebem estar sendo mal empregadas pelos outros. (p. 26)

> Por isso pareceu-me dino de consideração tentar descobrir sem em Roma era possível ordenar um estado que eliminasse tais controvérsias [entre povo e senado]. E, para examinarmos isso, é necessário recorrer ás repúblicas que sem tantas inimizades e tumultos permaneceram livres por longo tempo, vendo que tipo de estado nelas havia, e se era possível introduzi-lo em Roma. (p. 27)

> Considerando portanto tudo isso, vê-se que os legisladores de Roma precisariam ter feito uma destas duas coisas, se quisessem que Roma permanecesse tranquila como as repúblicas acima citadas: ou não empregar a plebe na guerra, como os venezianos, ou não abrir caminho para os forasteiros, como os espartanos. Mas fizeram ambas as coisas, o que deu à plebe força, número e infinitas ocasiões para criar tumultos. Mas, se o estado romano se tornasse mais tranquilo, decorreria o inconveniente de tornar-se também mais fraco, porque assim lhe era barrado o caminho para chegar à grandeza a que chegou: de tal modo que, se Roma quisesse eliminar as razçoes dos tumultos, eliminaria também as razões de ampliar-se. E em todas as coisas humanas quem bem examinar verá que nunca se pode anular um inconveniente sem que surja outro. (p. 29-30)

## Anotações de aula

A forma maquiaveliana de se aproximar do problema da política tem duas dimensões principais: comparativa e exemplar. A ideia de que o indivíduo age politicamente é compreensível a partir de uma previsibilidade que é dada pela história. 

Maquiavel n'O Príncipe diz: para obter o poder, ou você funda um principado, ou você herda, ou você toma o poder. Partindo essas possibilidades, o conjunto de exemplos históricos nos permite dizer quais circunstâncias levam a tais objetivos e quais são as situações em que determinadas atitudes falham. Não é porque a história se repete, mas porque o horizonte de atitudes possíveis é limitado. A ação dos indivíduos é previsível porque ela é sempre motivada por certos interesses, por certas paixões.

Uma boa forma de governo é aquela que, a despeito do conflito ser constante, ela continua sendo estável. Uma boa república é aquela na qual as leis garantem a liberdade dos cidadãos -- a "liberdade como não-dominação", como chamaram os republicanos contemporâneos o conceito de liberdade para Maquiavel. Sobretudo para a maioria, a liberdade passa pela ideia de que ela é algo que se faz no exercício da vida coletiva quando você não é simplesmente objeto do mando político das elites.

Também existe em Maquiavel, muito rapidamente, o problema das formas de governo. Mas aqui também existe uma ideia aristotélica (embora ele muito provavelmente não tenha lido Aristóteles) de que a excelência da constituição romana vem do fato de que ela conseguiu mesclar as três formas de governo em uma única constituição. 

E a plebe foi sendo bem sucedida em cada vez mais ampliar suas funções no tribunato, diminuindo a extensão do poder do Senado. A coisa começa a funcionar mal com aquilo que ficou conhecido posteriormente na história romana como a revolta dos Graco -- o que faz com as terras que são conquistadas? Quando a plebe começa a demandar redistribuição das propriedades conquistadas, o conflito se acirra porque as leis romanas não previram o que fazer com as terras. 

A república continua sendo boa na medida em que ela é capaz de processar os conflitos. As instituições deixam de ser capaz de dar solução ao conflito político nessa circunstância, não atendendo mais à finalidade para as quais elas foram desenhadas.

O conceito antitético, assimétrico da república para Maquiavel é a tirania (um lado conseguiu exercer o monopólio da violência), a guerra civil e a guerra de um Estado contra o outro. Nessas situações, não existe a possibilidade de criação de regras que gerem a estabilidade e, portanto, não existe ambiente para as instituições.

O que faz a república romana perfeita é o equilíbrio estático -- i.e., a desunião entre a plebe e o senado, oligárquico por natureza, já que quem compunha o senado eram os ricos donos de terra.

**“Senatus Populus Que Romanus”, ou “Senado e o Povo de Roma”**, os dois grupos que constituem Roma: o vínculo a essa comunidade política é que você tem dois grupos materialmente distintos, mas que permanecem unidos em uma comunidade por meio do conflito. 

Poderíamos dizer que a liberdade em Maquiavel é uma definição negativa -- isto é, proveniente da não-dominação. No entanto, exercer essa liberdade é algo absolutamente prático, em particular porque para exercer essa liberdade é necessário assumir uma série de funções políticas, limitando, inclusive, a atuação do Senado.

A dominação de novas terras acaba, de certa maneira, quebrando o equilíbrio dinâmico na medida em que as leis romanas não previam o que fazer com essas terras. No entanto, a dominação de novas terras garante, na prática, direitos políticos a quem as conquista -- afinal, os donos de terra compunham o Senado. Isso gera uma profunda crise. Para Maquiavel, não há compatibilidade possível entre a República e um dispositivo institucional que gere conflitos excepcionais a todo o tempo. Mesmo que não intencionalmente, isso provoca o fim da República.

Se o conflito é ao mesmo tempo um problema e a condição de liberdade do povo, pode ser que, numa certa leitura, isso seja visto num certo sentido como uma dimensão propriamente elitista da visão maquiaveliana. O que o Maquiavel não diz é que a plebe seria capaz de superar o conflito por um governo puramente popular -- essa possibilidade não está na mesa; afinal, ele não pensa num mundo fora dos conflitos permanentes. No horizonte, o que tá colocado é a possibilidade de novos conflitos políticos, que, no limite, são inescapáveis. Por isso a história das formas de governo é cíclica.

Quando a plebe se engaja na vida política de Roma, a ideia é recobrar a liberdade. O que produz a corrupção da república é a ausência dessa virtude. Maquiavel não espera que os mais ricos não se corrompam; antes, a ideia é que a plebe, no exercício da vida política, produza um constrangimento dos nobres.

Entenda que não existe pressuposição de uma ausência de violência. A violência está presente o tempo todo, mas, na prática, a república é capaz de processar a violência e evitar que ela escale para uma guerra civil. A república é capaz de processar a violência, mas não é capaz de eliminá-la.

A ideia de ditadura em Roma remete a um expediente constitucional para que em situações de risco pudesse haver um único homem com o poder de decidir. Na sua origem, o conceito não tem a ver com tirania, mas com a ideia de que, em situações excepcionais, é necessário que haja um único homem com o poder de decidir sem qualquer consulta ou apelação.

**Não há, para Maquiavel, um problema com o mecanismo institucional da ditadura**; mas, como todas as instituições da república, ela é passível da corrupção. É necessário que as instituições sejam capazes de lidar com situações de excepcionalidade -- e a ditadura é pensada como uma solução para esse problema. O mecanismo não é o problema, mas sim a ambição do ditador sob certas condições políticas e de instabilidade, que podem levar a uma tirania. No caso de César, por exemplo, a situação estava tão tensionada pela questão agrária que, para certos grupos, a ditadura militar apareceu como uma solução. A tirania, portanto, é resultado do não funcionamento das instituições.

A lei agrária era motivo de muito conflito. Os Gracos interpretavam que a lei agrária deveria ser aplicada às terras conquistadas pelo império, e não somente às terras de Roma. No entanto, aqueles que conquistaram as terras já não estavam dispostos a renegociá-las. Portanto, instaurou-se uma crise que já não podia mais ser processada por vias institucionais.