---
title: "Locke I "
author:
  - name: Felipe Lamarca
    email: felipelamarca@iesp.uerj.br
fontsize: 12pt
---

## Anotações de aula

O primeiro tratado é uma refutação de um tipo de discurso político muito importante naquele contexto; no segundo, ele fala da sua concepção de uma boa ordem, ou o que ele chama de "sociedade civil". 

No primeiro tratato ele escreve contra um sujeito chamado Robert Filmer, que escrevia sobre a legitimidade na Monarquia a partir da ideia de que o rei supostamente descenderia diretamente de Adão e Eva. A ordem política, nesse caso, seria um desdobramento natural da ordem divina. Mais que isso, violar o estado natural das coisas (i.e., a figura do rei) é ir contra os desígnios divinos.

Para Locke, a lei natural é aquilo que a própria natureza dos corpos físicos impõem como finalidade. Em particular, é instintivo que um Leão lute pela sua sobrevivência. No caso do ser humano, Locke reformula a ideia hobbesiana incluindo a propriedade dentre essas finalidades. A propriedade é uma maneira de manter as condições de reprodução dos indivíduos -- não apenas uma dimensão de medo da morte, mas de permitir a reprodução.

> O que estabelece a propriedade em Locke? A capacidade de o indivíduo transformar essa propriedade em recursos (o trabalho) para a sua sobrevivência. A princípio, essa definição poderia servir também para estabelecer limites à propriedade; por outro lado, a transformação da propriedade em produção possui um limite natural de que as pessoas não são capazes de consumir tudo que produzem. Isso sugere que as sobras deveriam ser reguladas, porque elas corrompem o ser humano. No entanto, Locke indica que a introdução do dinheiro evita essa ideia de perecibilidade da produção.
>
> O dinheiro insere um problema, mas não limita a propriedade. Em particular, o problema do Locke com a propriedade é o fato de que, no estado de natureza, a proteção da vida e da sociedade depende explicitamente do indivíduo.

Quando o rei viola a sua propriedade, ele retorna ao estado de natureza e, portanto, pode ser morto. A ideia de estado de natureza é quase um conceito analítico de controle para esses autores, de maneira que entendemos o que é legítimo e o que é passível de não-regulação (ou seja, permitindo interações violentas). Quando o indivíduo viola os critérios do contrato, ele se recoloca no estado de natureza e pode ser morto -- é assim que justifica o tiranicídio.

Para Locke, a comunidade política permanece ativa como sociedade civil (isto é, uma sociedade regulada por leis) quando você produz o contrato. Esse é um ponto em que se diferencia de Hobbes, caso em que o rei é absolutamente soberano. Em Locke, a comunidade não delega totalmente a representação, mas participa. Nesse caso, o problema da representação surge de modo mais explício: como instrumentalizar o autogoverno da comunidade?

A sociedade civil é algo diferente das instituições políticas, mas é justamente o critério de representatividade das instituições políticas por meio da representação. É a ideia de que existe um espaço para essa sociedade civil, que é composta pelos sujeitos da comunidade política; e, ao mesmo tempo, a sociedade civil é ao mesmo tempo a vida privada dos indivíduos. É o critério de vida privada e ao mesmo tempo o de representação. Esse é um ponto fundamental da teoria do Locke e que está longe da teoria do Hobbes, caso em que a sociedade civil é apenas a dimensão privada da vida dos indivíduos, que só é permitida porque a representação foi totalmente delegada à figura do rei, que garante a manutenção do contrato.

A decisão sobre a norma, sobre a lei, não é uma decisão discricionária do soberano; antes, possui um vínculo imediato com a sociedade civil. A legitimidade da ordem política está na sociedade, e todo o vocabulário da democracia liberal vai ser construído em cima dessas ideias.