# Teoria Política e História das Ideias Políticas

## Anotações de aula

Teoria política deve ser pensada sobretudo como uma intervenção linguística no mundo social -- ela é por si só um ato que tem a pretensão de produzir efeitos no mundo social. Se fôssemos definir a tradição de Skinner e Pocock, da Escola de Cambridge, seria essa.

Agora, no caso de Koselleck, que fundamenta uma tradição da história dos conceitos, pensa a teoria política como algo indissociável da história. Os conceitos políticos são fundamentalmente se intervem no mundo político. São diagnósticos sobre uma determinada ordem política pensando em produzir efeitos sobre ela.

### Koselleck (2006)

Por uma questão cronológica, vamos começar pelo Koselleck.

O tipo de experiência que o mundo social nos permite ter é limitado pelos conceitos que usamos para representar esse mundo. Se em algum momento não houve uma discussão aprofundada sobre redistribuição de renda, isso ocorreu em certa medida porque o próprio conceito de igualdade não estava presente da maneira que está hoje. Os conceitos são a ferramenta que os atores utilizam para intervir no mundo social.