---
title: "Teoria Política e História das Ideias Políticas"
author:
  - name: Felipe Lamarca
    email: felipelamarca@iesp.uerj.br
fontsize: 12pt
---

# Teoria Política e normatividade

## Anotações das leituras

### WALDRON, Jeremy. Political Polítical Theory. Cambridge: Harvard University Press, 2016 (Capítulo 1. “Political Political Theory”).

> Institutions or the character of those who inhabit them? Should students of politics make a study of the one or the other? Both, surely, would be the obvious answer. They should understand something of political virtue and the demands that the requirements of good government make on the character of those who take on the responsibility for public affairs, even if there is no more than the ethic of responsibility that Max Weber recommended. But maybe there is a special reason for studying institutions: to understand the ways in which institutional forms can be designed so as to outwit and outflank what Hume called "the casual humours and characters of particular men". (p. 1)

> Hume seems to have believed that political science would be impossible if everything depended on individual character. There would be no political science, just bedside biographies. Fortunately for the scientist, however, "the force of laws, and of particular forms of government" is so great and has "so little dependence... on the humours and tempers of men, that consequences almost as general and certain may sometimes be deduced from them," such as those we can deduce in the natural and mathematical sciences. (p. 2)

> Perhaps we need to replace Hume's dichotomy with a tri-chotomy, so that the question now is whether we should direct our theoretical energy to questions about (1) the individual virtues that good governance requires, (2) the political institutions that are needed in a good society composed of humans rather than angels, or (3) the ends and ideals that a good society should be seeking to promote. I think it is fair to say that, for some time now, the main focus in political theory has been on (3), the ends and ideals that a good society should seek to promote.

#### Isaiah Berlin

> To read almost any of Berlin's work is to read essays that are resolutely uninterested in the political institutions of liberal society. Beyond airy talk of freedom and openness, Berlin was simply concerned with the ways in which liberal or democratic political institutions might accomodate the pluralism he thought so important in human life (p. 4-5)

#### Topics and principles

> It is time to lay my own cards on the table. I think institutions are massively important. Exactly because we disagree in our ethical and political aims, we need to inquire into the structures that are to house and refine our disputes and the processes that are to regulate the way we solve them. I mean the processes by which we (in our millions) resolve disagreements over disparate aims that we severally regard as fundamentally important -- without degenerating into fighting driven either by self-interest or worse still by the militias of self-righteousness. (p. 5-6)

> This is what I mean by _political_ political theory --- theory addressing itself to politics and to the way our political institutions house and frame our disagreements about social ideals and orchestrate what is done about whatever aims we can settle on. (p. 6)

> Institutions make a difference, not just in the political game but, through the inclusiveness of the order they stablish, to the security, prosperity, and openness of the societies in which they are established. 

#### The value of institutions

> Very well, you may say, but isn't the study of institutions and political processess a matter for empirical political science? [...]. Well, yes and no. Certainly it is a task for political science. The study of how politics actually works within the institutions we have established is the immense and challenging agenda of political science, one that I greatly respect and that political theorists should take much more notice of and dovetail their work with.
> 
> But that does not preclude the reflective interest of political theory. Institutions are theoretical matters too. And not just for what is sometimes called "positive" political theory. The study that I am envisaging is emphatically normative, for we have _choices_ to make about our institutions and processes. (p. 8)

### KELLY, Paul. “Rescuing political theory from the tirany of history”. In: Floyd, Jonathan, and Marc Stears, eds. 2011. Political Philosophy versus History? Contextualism and Real Politics in Contemporary Political Thought. Cambridge: Cambridge University Press.

> What is at issue is how far we should push this acnowledgement of the claims of history for any viable political philosophy (p. 13)

> My concern in this chapter will be to contest the bold claims for history as a constraint upon normative political philosophy -- what one might call the tyranny of history over political philosophy. The argument will begin with an outline of what I call the Collingwoodian paradigm and its subordination of political philosophy to history. [...]. I intend to argue that contrary to the claims of MacIntyre, Skinner, Williams and Geuss, the turn to history must be subordinate to the demands of philosophical justification. Consequently, rather than making a case against the possibility and value of historical construction, the acknowledgement of history is the sort claimed by Geuss provides only useful supplementary material to a proper political philosophy. (p. 15)

## Anotações de aula

Existe um momento do pós-guerra em que a academia americana fica apegada à teoria normativa do Rawls, pensando sobretudo a partir de abordagens katianas da teoria da justiça. 

Kelly está escrevendo profundamente contra o Skinner (uma ideia contextualista) em detrimento de uma defesa . O contexto não é um dado objetivo da reflexão teórica. A própria ideia de ordem política, instituição como algo que estabiliza a ordem, enfim. Existem coisas que não são determinadas pelo contexto e, ao mesmo tempo, o contexto só muda na medida em que o autor é capaz de propor uma ruptura com a linguagem estabelecida.

Não é a ideia de jogar o contexto fora, mas entender que a normatividade é indissociável, sobretudo quando você faz uma crítica. Na medida em que a teoria política também é crítica das instituições políticas, trata-se também de uma questão normativa. Então, pensar que você pode assumir uma postura de neutralidade em relação ao contexto é um equívoco.

É da natureza da reflexão política fazer uma definição normativa sobre o que é uma boa ordem e o que é uma má ordem. A ideia de contexto é mais limitadora do que necessária: a resposta para certos problemas políticos não é uma resposta contextual; há, na verdade, uma série de problemas que são transversais à política. O ponto central é entender que é indissociável da reflexão política uma natureza normativa (normatividade num sentido geral: indica um sentido positivo e um sentido negativo para a ação política dos indivíduos).

A teoria normativa é a teoria de justificação de certas instituições políticas -- ela argumenta os motivos, remetendo a certos valores, de algumas instituições serem boas e outras ruins. A partir dessa discussão, há a defesa de uma certa teoria universal da justiça (no caso da Rawls). E, ainda no caso do Rawls, o problema motivador da sua teoria era um problema hegemônico na ciência política americana enquanto ele escrevia: a teoria da ação coletiva e a teoria da escolha racional -- como os indivíduos cooperam para fazer valer o seu interesse de grupo.

A primeira questão do Rawls é reecontrar a pergunta sobre como produzir uma ordem justa, isto é, uma ordem que aloque esses recursos de modo equitativo. Essa pergunta **SÓ** pode ter uma resposta normativa. Há certas perguntas que a investigação sobre a política faz que só podem ter respostas de natureza normativa, porque elas pressupõem suposições fortes sobre como a sociedade deve se organizar para atingir determinado fim.

O ponto do Rawls é que a teoria da justiça se aplica sobre o problema da desigualdade. Ela (a teoria da justiça) não surge do nada: precisamos pensar numa ordem institucional que seja capaz de lidar com as desigualdades.

Rawls é fundamentalmente um contratualista: a estrutura básica é objeto de um contrato. E o contratualismo é sobretudo uma abstração para pensar sobre o "momento 0" -- referente à desordem -- e o "momento 1" em que os princípios da boa ordem se estabelece entre os indivíduos. Nesse sentido, o que a gente pode dizer é que uma teoria de natureza contratualista é **SEMPRE** normativa. O próprio contrato é uma abstração sobre o consenso que os indivíduos devem ter sobre a ordem política. É nesse sentido que insistimos que é impossível pensar teoria política fora da sua dimensão normativa: se estamos avaliando o mundo político o tempo todo, e diferenciando processos políticos bons e ruins, conflituosos e não conflituosos, ela é normativa em essência.

Instituições podem ser pensadas como um conjunto de regras que transpõe, para a arena da política institucionalizada, o conflito que existe para muito além dessas regras (e que podem, evidentemente, desestabilizá-las). O mundo do conflito está para muito além das instituições, e se as instituições não limitam esses conflitos, é o "apelo aos céus" de Locke. Todos esses autores sabem que a sociedade pode produzir um conflito que está para além da capacidade das instituições de lidar com ele.

> Não dá para não distinguir o conflito que é político (aquele que pode ser mediado por regras) e o conflito que não é político. Para compreensão de um campo do conhecimento, essa distinção é fundamental.

Waldron chama atenção para as instituições políticas que são criadas a partir do conflito, e não do consenso. A teoria política _política_ reflete sobre outros arranjos organizativos que não necessariamente dizem respeito aos princípios de justiça básicos. A teoria política é também uma reflexão sobre como o poder está distribuído na sociedade e como ele é exercido de modo legítimo. No fim das contas, é uma teoria política _institucional_ e, no limite, uma teoria democrática.